### ISSUE TITLE
todo) home, main, user/edit 페이지 스타일링 

### ISSUE THREAD

**Issue by hwisaac** [FastcampusMini/mini-project-fe#2]
- [x] Home 페이지 스타일링
- [x] `/main` 메인 페이지
    - 신청 가능 대출금 총합
    - 현재 신청 가능한 대출 상품들
- [x] `user/edit` 페이지
    - 정보수정 form : 패스워드/이름/나이/직업/거주지/특기/취미/연봉
    - 확인 버튼 - "PUT api/user"

> Home
<img width="513" alt="image" src="https://user-images.githubusercontent.com/54179672/218394228-f69d3718-6d6a-48b0-a848-e9477649a787.png">

> Main
<img width="531" alt="image" src="https://user-images.githubusercontent.com/54179672/218454400-ba17fcd8-c29a-4565-bc84-abdc2fcb710f.png">

> user/edit
<img width="534" alt="image" src="https://user-images.githubusercontent.com/54179672/218435095-9e5031bd-9a0f-45b0-b48e-0cbdeef1d657.png">
